# Configuration for probot-auto-merge - https://github.com/bobvanderlinden/probot-auto-merge

updateBranch: true
deleteBranchAfterMerge: true
reportStatus: true

minApprovals:
  COLLABORATOR: 2
maxRequestedChanges:
  NONE: 0
blockingLabels:
- blocked